### ISSUE TITLE
Missing Teaching Content - Suggestion to Modify Section or Add New Navigation

### ISSUE THREAD

**Issue by bishal784411** [RelevantResearch/penelopeanthias#12]
I have noticed that there are no contents available in the "Teaching and Impact" section. This section seems necessary for providing users with valuable information on the subject. Should I modify an existing section to include relevant content, or is it better to add a completely new section under the navigation? Please provide guidance on the best approach to resolve this.

**Comment by austinkocher** [comment]
Good question. We will add content there, but before we do, I want to ask the client to review the website with me over Zoom so that we can just make sure things are going how they hope. I would say that, in general, there isn't too much more content to update on this particular website because you already did a very thorough job. After I meet with the client, we should be able to update everything to its final location.

**Comment by bishal784411** [comment]
Should I modify an existing navigation i.e. changing 'impact' to 'Books'  , or is it better to add a completely new  navigation? Please provide guidance on the best approach to resolve this.

**Comment by austinkocher** [comment]
I suggesting that we add a totally new navigation button.
